# Generated by Django 5.2.1 on 2025-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cuentacontable_clasificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
