# Generated by Django 5.2.1 on 2025-09-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_asientocontable_actualizado_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
    ]
