# Generated by Django 5.2.6 on 2025-09-10 19:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0002_cuentacontable_clasificacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rif', models.CharField(max_length=20, unique=True, verbose_name='RIF')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/Razón Social')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('tipo_proveedor', models.CharField(choices=[('PJ', 'Persona Jurídica'), ('PN', 'Persona Natural')], default='PJ', max_length=2, verbose_name='Tipo de Proveedor')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Compra')),
                ('numero_factura', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('numero_control', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Control')),
                ('planilla_importacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Planilla de Importación')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Incluye IVA')),
                ('base_imponible_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Base Alicuota General (16%)')),
                ('impuesto_general', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuesto Alicuota General')),
                ('base_imponible_reducida', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Base Alicuota Reducida (8%)')),
                ('impuesto_reducido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuesto Alicuota Reducida')),
                ('base_imponible_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Base Alicuota Adicional (22%)')),
                ('impuesto_adicional', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Impuesto Alicuota Adicional')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.asientocontable', verbose_name='Asiento Contable')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-fecha'],
                'unique_together': {('proveedor', 'numero_factura')},
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
            },
        ),
    ]
